### ISSUE TITLE
Mark official holidays

### ISSUE THREAD

**Issue by filipvanlaenen** [filipvanlaenen/wruf#1]

**Comment by filipvanlaenen** [comment]
Remaining functionality:

- Handle observed separately in `wruf init`
- Handle informal separately in `wruf init`
- Verify whether the strings are recognized regions
- Possibility to list the recognized regions

**Comment by filipvanlaenen** [comment]
Bug:

```
$ wruf current dislike
/usr/lib/ruby/3.0.0/psych.rb:274:in `load': unknown keyword: :permitted_classes (ArgumentError)
	from /opt/wruf/lib/wruf_settings.rb:31:in `load'
	from /opt/wruf/lib/wruf.rb:47:in `load_settings'
	from /opt/wruf/lib/wruf.rb:53:in `load'
	from /opt/wruf/wruf_current_dislike.rb:24:in `<main>'
$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```
